### ISSUE TITLE
Add events page

### ISSUE THREAD

**Issue by Banta** [nairuby/nairuby.github.io#36]
We would like to have events page on nairuby.org websites. The following events should be added;
* Ruby workshop - http://www.eventbrite.com/e/ruby-workshop-tickets-16154746281?aff=ehomefriend
* Ruby conference - https://www.eventbrite.com/e/rubyconf-ke-2015-tickets-15386615782

**Comment by itsmrwave** [comment]
Done ... http://nairuby.org/events/.

One day I'll work on the design and add a few more images, there's too much text but it works for now.

**Comment by Banta** [comment]
Thanks @itsmrwave

**Comment by iamleader** [comment]
You are awesome @itsmrwave‎.                                                                                                                                                                                                                                                                           Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                                         From: itsmrwaveSent: Thursday, March 19, 2015 18:17To: nairuby/nairuby.github.ioReply To: nairuby/nairuby.github.ioSubject: Re: [nairuby.github.io] Add events page (#36)Closed #36.

—Reply to this email directly or view it on GitHub.
